### ISSUE TITLE
视频剪裁

### ISSUE THREAD

**Issue by cwghnu** [yangjie10930/EpMedia#176]
在API为23的的手机上第一次剪裁可以通过，第二次则显示保存失败，程序没有崩溃，同样的代码在API为19的手机上则没有

**Comment by yangjie10930** [comment]
能提供下log吗

**Comment by cwghnu** [comment]
------ beginning of crash
11-02 21:04:54.720 1828-1828/com.example.jyang022.testopencv E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.jyang022.testopencv, PID: 1828
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.jyang022.testopencv-1/base.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.jyang022.testopencv-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.jyang022.testopencv-1/lib/x86, /data/app/com.example.jyang022.testopencv-1/base.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.example.jyang022.testopencv-1/split_lib_slice_9_apk.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libavfilter.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at Jni.FFmpegCmd.<clinit>(FFmpegCmd.java:22)
        at Jni.FFmpegCmd.exec(FFmpegCmd.java)
        at VideoHandle.EpEditor.execCmd(EpEditor.java:636)
        at VideoHandle.EpEditor.exec(EpEditor.java:133)
        at com.example.jyang022.testopencv.CameraActivity.saveVideo(CameraActivity.java:241)
        at com.example.jyang022.testopencv.CameraActivity.access$1200(CameraActivity.java:48)
        at com.example.jyang022.testopencv.CameraActivity$5.onClick(CameraActivity.java:288)
        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    
    可以麻烦看下怎么解决吗
