### ISSUE TITLE
No implementation found for int Jni.FFmpegCmd.exec

### ISSUE THREAD

**Issue by AndSync** [yangjie10930/EpMedia#190]
执行报错 什么原因呢？
````
EpVideo epVideo = new EpVideo(model.getPath());
                epVideo.rotation(360-rotate,false);
                EpEditor.OutputOption outputOption = new EpEditor.OutputOption(model.getClipPath());
                EpEditor.exec(epVideo, outputOption, new OnEditorListener() {
                    @Override
                    public void onSuccess() {
                        mHandler.obtainMessage(MSG_FINISH).sendToTarget();
                    }

                    @Override
                    public void onFailure() {

                    }

                    @Override
                    public void onProgress(float progress) {
                        //这里获取处理进度
                    }
                });
````
````
java.lang.UnsatisfiedLinkError: No implementation found for int Jni.FFmpegCmd.exec(int, java.lang.String[]) (tried Java_Jni_FFmpegCmd_exec and Java_Jni_FFmpegCmd_exec__I_3Ljava_lang_String_2)
        at Jni.FFmpegCmd.exec(Native Method)
        at Jni.FFmpegCmd.exec(FFmpegCmd.java:75)
        at VideoHandle.EpEditor.execCmd(EpEditor.java:636)
        at VideoHandle.EpEditor.exec(EpEditor.java:133)
        at com.taoche.qctt.ui.editor.activity.VideoEditRotateActivity.onClickEvent(VideoEditRotateActivity.java:138)
        at com.taoche.qctt.ui.base.BaseCustomActivity.onClick(BaseCustomActivity.java:140)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22465)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6388)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
````

**Comment by xkn874** [comment]
志敏你好，请问这个问题你解决了吗？我也遇到这个问题了，万分期待你的回复。
时间紧迫，望回复！！！！！！

**Comment by AndSync** [comment]
@xkn874 感觉是路径问题 弃坑了 https://github.com/microshow/RxFFmpeg

**Comment by hanswimtj** [comment]
同问
